### ISSUE TITLE
updating debian broke integration [solution]

### ISSUE THREAD

**Issue by juulius** [Ekman/home-assistant-pure-i9#47]
Hi

first thanks for the integration for home assistant. 
after updating debian to latest (update and upgrade) this integration somehow broke, it couldn't login anymore to AEG

after some digging i changed every import purei9_unofficial.cloudv2 to purei9_unofficial.cloudv3
and in de manifest changed  "requirements": ["purei9_unofficial==0.0.11"] to  "requirements": ["purei9_unofficial==0.0.12"]. (this is the latest release)

that got it working again, dont know if anything changed with cloudv2 API call or something

**Comment by Phype** [comment]
Updating debian shouldn't have caused the problem, but the old API seems to be down:

https://github.com/Phype/purei9_unofficial/issues/25
https://github.com/JohNan/homeassistant-wellbeing/issues/53

I'm not expecting it to work again since the electrolux app which is based on it was deprecated already, so we have to change to the new API.

**Comment by juulius** [comment]
had already a feeling that it was the API. 
but had a "if it works dont update" kind of a mindset :P

**Comment by Ekman** [comment]
Thanks @juulius for reporting the issue and thanks @Phype for being quick to respond, I really appreciate it.

I've merged a PR #48 by @lorenzo-deluca that fixes the issue, and I've just released a new version of the integration [1.4.1](https://github.com/Ekman/home-assistant-pure-i9/releases/tag/1.4.1).
